name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build:
    name: "Build - UI"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install NPM dependencies
        run: npm install
        working-directory: web

      - name: Build UI
        run: npm run build
        working-directory: web

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            web/build

  deploy:
    name: "Deploy UI"
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Install Az SWA CLI
        run: npm install -g @azure/static-web-apps-cli

      - name: Deploy UI
        run: |
          swa deploy static \
          --api-location server \
          --env production \
          --api-language "node" \
          --api-version "22" \
          --deployment-token ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} \
          -name un-quizzes

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
